publishdir = "public"
static = "/static"
builddrafts = false
buildFuture = true
# Replace this with your website URL
baseurl = "https://neuralnetworkingnight.github.io/"
canonifyurls = true
theme = "hugo-academic-group"
languageCode = 'en-us'
title = "Neural Network Night"
math = true
copyright = "&copy; Neural Networking Night, 2024 "

[taxonomies]
  category = "categories"
  tag = "tags"

[params.meta]
  favicon = true

[params]
  description = "Website of the Neural Networking Night seminar series in a pub"
  author = "Michael Graupner"
  email = "neuralnetworkingnight@listes.u-paris.fr"
  address = "Le Piano Vache, <a href='https://maps.app.goo.gl/JuB9ZnnEf1F9dSsk8'>8 Rue Laplace, 75005 Paris</a>"
  slogan = "Neural Networking Night"
  textbox = "The _Neural Networking Night_ is held at the iconic student pub __Le Piano Vache__ (8 Rue Laplace, 75005 Paris), located in the academic heart of Paris. Seminars take place on __Fridays at 5 pm__ and are followed by time for informal conversations and socializing. \n Write an email to <a href=\"mailto:sympa@listes.u-paris.fr?subject=subscribe%20neuralnetworkingnight@listes.u-paris.fr\">sympa@listes.u-paris.fr</a> with the subject _subscribe neuralnetworkingnight@listes.u-paris.fr_ if you want to be added to our mailing list."
  #slogan_text = "Re-evaluating the role of the Cerebellum "
  #slogan_icon = "icon-spsbrats_logo"
  custom_css = ["neuralnetworkingnight.css"]
  gtm_id = "G-P6PPEWJE9S"
  gtm_ga = true

[params.logo]
    image = "img/logo-NNN.png"
    link = "https://neuralnetworkingnight.github.io/"
    position = 1

#[[params.navbar_hierarchy]]
#    name = "DEC"
#    link = "https://cognition.ens.fr/en"
#    position = 1

#[[params.navbar_hierarchy]]
#    name = "LNC2"
#    link = "https://lnc2.dec.ens.fr/en"
#    position = 2

#[[params.navbar_hierarchy]]
#    name = "GNT"
#    link = "https://gnt.dec.ens.fr/en"
#    position = 3

[[params.sponsors]]
    name = "DIM C-BRAINS"
    link = "https://dim-cbrains.fr/fr/home"
    image = "/img/sponsors/logo_new_blank_frame.png"

#[[params.sponsors]]
#    name = "Région Île-de-France"
#    link = "https://www.iledefrance.fr/"
#    image = "/img/sponsors/region-idf-logo.png"


#  [[params.slogan_columns]]
#    title = "."
#    text =  "."
#    link = "/"
#    link_text = ""
#    weight = 1
  
  #[[params.slogan_columns]]
  #  title = "Mission"
  #  text = "Per peterem ex, Eurystheus videt maeonis, Paeonis uritur. Dextera [legem](http://nubibus.net/qualisardeat), contigerat optabile undis bene: abis sperato. Instrumenta arma, subiectas generis non ipsa patres quia magna Messeneque lacrimaeque torva. Aequo crescunt inrequieta feras, diu illa est occupat aequoribus hunc Elpenora tollens vult robore. Finiat priora vulnere nec Nelei fit quae totidemque intibaque iter longo."
  #  link = "/mission"
  #  link_text = "Read more"
  #  weight = 2

  #[[params.slogan_columns]]
  #  title = "Approach"
  #  text = "Lorem markdownum in texit! Quoniam ferar tabellis modo! Nam et spatiosumque puellae modo temperiemque mare canentis ministris **populisque** actus flammifera [dicta](http://www.geminoalpino.com/nec-pegason), non neque nutrit [recingunt Phrygiae](http://vitta-telamone.org/cyllenenquearcus.php). Pignoribus Phaestia Chaonis simulacraque viae et genus miratur moenibus tinnitibus ex simul."
  #  link = "/approach"
  #  link_text = "Read more"
  #  weight = 2

  # Selected Publications section.
  [params.publications_selected]
    detailed_list = true
    title = "Selected Publications"
    subtitle = ""

  # Publications section.
  # Section will only be displayed if there are publications in `content/publication/`.
  [params.publications]
    count = 3
    detailed_list = false
    title = "Publications"
    subtitle = ""
    str_all = "More Publications"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 2
    detailed_list = true
    title = "About the event"
    subtitle = ""
    #str_all = "More Posts"
    str_read_more = "Read more"

  # Projects section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.projects]
    title = "Upcoming Events"
    subtitle = "All seminars take place in the __Le Piano Vache bar__ (8 Rue Laplace, 75005 Paris) and start at __5 pm__ (see below)."
    count = 3
    str_all = "More Events"
  
  # Vacancies section
  # Section will only be displayed if there are valid vacancies in `content/vacancy`
  #[params.vacancies]
  #  title = "Vacancies"
  #  subtitle = ""
  #  count = 3
  #  str_all = "More Vacancies"

  # Contact section.
  [params.contact]
    enable = true
    title = "Location and Time"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # About section.
  [params.about]
    enable = true
    title = "About the Event"
    subtitle = ""
    autolink = false  # Automatically link email and phone?

  # Navigation Links
  #   The weight parameter defines the order that the links will appear in.

  [[menu.main]]
      name = "Home"
      url = "/#top"
      weight = 1

  [[menu.main]] # Research = [Projects, Publications, Blog]
      name = "All Events"
      url = "/project"
      weight = 2

  [[menu.main]] # Research = [Projects, Publications, Blog]
      name = "About the event"
      url = "/#posts"
      weight = 3

#  [[menu.main]] # Research = [Projects, Publications, Blog]
#      name = "About the Event"
#      url = "/about"
#      weight = 4
#
#      [[menu.main]]
#        name = "Projects"
#        url = "/projects"
#        parent = "research"
#        weight = 3
#      [[menu.main]]
#        name = "Overview"
#        url = "/overview"
#        parent = "research"
#        weight = 1
#      [[menu.main]]
#        name = "People"
#        url = "/member"
#        parent = "research"
#        weight = 2
  [[menu.main]]
    name = "Organizers"
    url = "/organizers"
    weight = 5


#    [[menu.main]]
#      name = "Projects"
#      url = "/#projects"
#     weight = 0


#  [[menu.main]]
#      name = "News"
#      url = "/post"
#      weight = 4


  [[menu.main]]
      name = "Location and Time"
      url = "/#contact"
      weight = 4
